//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 07:36:25 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bcit.ca/comp4655/jaxb/address", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ca.bcit.comp4655.jaxb.address;
